### DISCUSSION TITLE
Tips installing `nanonext` on GitHub Actions

### DISCUSSION THREAD

**Discussion by wlandau** [r-lib/nanonext#7] [General]
I am having trouble installing `nanonext` on GitHub Actions. Apparently the `r-universe` binaries are not available (c.f. https://github.com/wlandau/crew/actions/runs/4325114051/jobs/7550840383), and compiling from the source has not worked on my end (https://github.com/wlandau/crew/actions/runs/4325026014/jobs/7550630546). How would you recommend I modify https://github.com/wlandau/crew/blob/main/.github/workflows/check.yaml to make the workflows succeed?

**Comment by shikokuchuo** [comment]
No need to install binary on GitHub. Just enable the r-universe repo. You can reference the mirai GH action.Actually just wait a day or so. New version of nanonext will be on CRAN. It is literally stuck in a queue! Infrastructure issue at CRAN Uwe is looking into it.On 3 Mar 2023, at 16:06, Will Landau ***@***.***> wrote:﻿
I am having trouble installing nanonext on GitHub Actions. Apparently the r-universe binaries are not available (c.f. https://github.com/wlandau/crew/actions/runs/4325114051/jobs/7550840383), and compiling from the source has not worked on my end (https://github.com/wlandau/crew/actions/runs/4325026014/jobs/7550630546). How would you recommend I modify https://github.com/wlandau/crew/blob/main/.github/workflows/check.yaml to make the workflows succeed?

**Reply by wlandau** [reply]
Fantastic! I will await the CRAN release.

**Reply by shikokuchuo** [reply]
Is now on CRAN.

FYI if you ever need to use dev nanonext on GH actions in future,
add:
```yaml
      - name: Add r-universe to repos
        run: |
          cat("\noptions(repos=c(shikokuchuo='https://shikokuchuo.r-universe.dev',CRAN ='https://cloud.r-project.org'))\n", file = "~/.Rprofile", append = TRUE)
        shell: Rscript {0}
```
before setup-r-dependencies:
```yaml
      - uses: r-lib/actions/setup-r-dependencies@v2
```
